on:
  pull_request:

test:
  runs-on: ubuntu-latest
  steps:
    # Clone repo
    - uses: actions/checkout@v2
    # Install JDK
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # Execute unit tests
    - name: Unit Test
      run: ./gradlew testDebugUnitTest