name: Build an app

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clone repo
      - uses: actions/checkout@v2
      # Install JDK
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Build project
        run: ./gradlew assembleDebug
      - name: Upload debug version
        uses: actions/upload-artifact@v2
        with:
          name: debug
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Echo ref
        run: echo ${{github.ref}}
      - name: Generate API documentation
        if: ${{github.ref == 'refs/heads/master'}}
        run: ./gradlew dokkaHtml
      - name: Deploy API documentation to Github Pages
        if: ${{github.ref == 'refs/heads/master'}}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: app/build/dokka/html
