name: Build docs & deploy to github

on:
  push:
    branches:
      - master
jobs:
  runs-on: ubuntu-latest
    steps:
    - name: Echo ref
      run: echo ${{github.ref}}
    - name: Generate API documentation
      if: ${{github.ref == 'refs/heads/master'}}
      run: ./gradlew dokkaHtml
    - name: Deploy API documentation to Github Pages
      if: ${{github.ref == 'refs/heads/master'}}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH: gh-pages
      FOLDER: app/build/dokka/html