name: docs

on:
  push:
    branches:
      - master
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # Clone repo
      - uses: actions/checkout@v2
      # Install JDK
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Echo ref
        run: echo ${{github.ref}}
      - name: Generate API documentation
        if: ${{github.ref == 'refs/heads/master'}}
        run: ./gradlew dokkaHtml
      - name: Deploy API documentation to Github Pages
        if: ${{github.ref == 'refs/heads/master'}}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: app/build/dokka/html